language: node_js

node_js:
  - 0.8
  - "0.10"
  - 0.11

branches:
  only:
    - master

before_install:
  - npm install -g bower grunt-cli
  - npm install
  - bower install

matrix:
  fast_finish: true
